### ISSUE TITLE
Getting ERR_ADDRESS_INVALID while accessing http://0.0.0.0:8080/

### ISSUE THREAD

**Issue by 1mgtheboss** [infermedica/js-symptom-checker-example#1]
I appreciate the efforts infermedica team has put into the development of the api. A big thanks to @TomaszGabrysiak for uploading this symptom checker on github. It will serve as an excellent starting point for developers interested in the api. I've cloned the repository and gone through the process. At the last step, i.e. after running `yarn dev` I'm getting `webpack: Compiled successfully` in the end, but when I'm accessing `http://0.0.0.0:8080/` I'm getting `ERR_ADDRESS_INVALID`. Is there anything I'm missing? Version information: os: windows 7 professional 32 bit, node: 6.11.0, npm: 3.10.10, yarn: 0.27.5, & webpack: 2.2.1.

**Comment by iwaszko** [comment]
@MGTHEBOSS thank you for the kind words!

Let's start with something very simple - could you try accessing http://127.0.0.1:8080/ instead?

**Comment by 1mgtheboss** [comment]
@iwaszko You're welcome. 

The url, [http://127.0.0.1:8080/](http://127.0.0.1:8080/) is loading Symptom Checker Example without any problem.

**Comment by iwaszko** [comment]
Great, I guess 0.0.0.0 is not recognized on Windows. @TomaszGabrysiak we should try to use 127.0.0.1 by default in the future.

**Comment by TomaszGabrysiak** [comment]
Changed.
