### ISSUE TITLE
Bundle.js not found 

### ISSUE THREAD

**Issue by wanching0730** [infermedica/js-symptom-checker-example#2]
When running the http server, the bundle.js is not found. We have installed yarn. Yarn version is 1.3.2. 
Seeking for help and thank you.

**Comment by TomaszGabrysiak** [comment]
Hi @wanching0730 ,

You have to build the app first, before serving content with http server. Please run `yarn build` and try again. 
Hope it helped. Please let me know if you have any additional questions.
