### ISSUE TITLE
can't select - radio button missing when selecting 

### ISSUE THREAD

**Issue by moubymoud** [infermedica/js-symptom-checker-example#4]
Hello, 
how can i resolve this issue ? i can't select anything. 

give me somes hint, i'm brand new with that. 

![screenshot 1](https://user-images.githubusercontent.com/46818012/51390970-bf155980-1b28-11e9-8224-34bed63d2f43.png)

**Comment by TomaszGabrysiak** [comment]
Hi @moubymoud. Did you make any changes in the code or the bug exists in the version from this repository? I'll check it on Monday and will come back to you with the solution.

**Comment by TomaszGabrysiak** [comment]
@moubymoud I checked it and it seems that radios are invisible due to newer version of bootstrap you're probably using. I'll implement a fix soon.

**Comment by moubymoud** [comment]
Thank's for the response.

Hope's that will go well soon.

Which version of bootstrap work the best with that ?

Le jeu. 31 janv. 2019 16:31, Tomasz Gabrysiak <notifications@github.com> a
écrit :

**Comment by TomaszGabrysiak** [comment]
@moubymoud please pull the changes and try again. Everything should work fine :) Let me know.
