### ISSUE TITLE
NLP doesn't respond when infermedica is in french " infermedia-fr" instead of "infermedica-en"

### ISSUE THREAD

**Issue by moubymoud** [infermedica/js-symptom-checker-example#5]
Hello, 

I would like to use infermedica in French, for that I modified in the source code "infermedica-en" to "infermedica-fr" and it works, except that for the NLP, it does not recognize any words from French or English. 

I would like to know, what are the manipulations to do, starting from zero to make it in French. Or if I did something wrong. 

The business developper has enabled french for me, so, no issue at that point. 

Thank you in advance, I'm short of ideas.

**Comment by TomaszGabrysiak** [comment]
Hi @moubymoud,

Unfortunately at the time we don't support NLP in French.

Please try `/search` endpoint which is supported in French and allows you to parse texts looking for medical concepts.

**Comment by gitNovaCorp** [comment]
Hello,

I would like to use infermedica in Spanish, for that I modified in the source code "infermedica-en" to "infermedica-es" and it works, except that for the NLP, it does not recognize any words from French or Spanish. Is possible?
