### ISSUE TITLE
Cannot find module ' eslint-plugin-standard'

### ISSUE THREAD

**Issue by faixal** [infermedica/js-symptom-checker-example#6]
1. Root directory -> yarn install
2. yar dev

Gives below error:

Module build failed: Error: Failed to load plugin standard: Cannot find module '
eslint-plugin-standard'

![image](https://user-images.githubusercontent.com/8006233/52976637-10488f80-33ec-11e9-93ad-06f2b6f48780.png)

**Comment by TomaszGabrysiak** [comment]
Couldn't reproduce. The error says that plugin named `eslint-plugin-standard` is missing. Please check if you have it installed and if not please install it manually.
